version: '3.8'

services:
  awesome_app:
    image: node:18
    container_name: nextjs-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install && npm run dev"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - "traefik.http.routers.awesome_app.entrypoints=websecure"
        - "traefik.http.routers.awesome_app.tls=true" 
        - "traefik.http.routers.awesome_app.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.awesome_app.rule=Host(`app.awesome.com`)"
        - "traefik.http.services.awesome_app.loadbalancer.server.port=9999"
        - "traefik.http.routers.awesome_app.service=awesome_app"
    networks:
      - my_awesome_network

networks:
  my_awesome_network:
    external: true
    name: my_awesome_network